name: packer

on:
  - push
  - pull_request

env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"

defaults:
  run:
    shell: powershell
    
jobs:
  packer:
    runs-on: windows-2019
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Uninstall Visual Studio Enterprise
        run: |
          Invoke-WebRequest -Uri 'https://aka.ms/vs/16/release/vs_Enterprise.exe' -OutFile 'vs_Enterprise.exe'
          Start-Process -Wait -FilePath '.\vs_Enterprise.exe' -ArgumentList 'uninstall', '--installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"', '--quiet', '--norestart', '--wait', '--nocache'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Run `packer init`
        id: init
        run: "packer init ./images/windows/templates/windows-2019-builds.pkr.hcl"
      - name: Run `packer validate`
        id: validate
        run: "packer validate ./images/windows/templates/windows-2019-builds.pkr.hcl"
      - name: Build Artifact
        run: packer build -color=false -on-error=abort ./images/windows/templates/windows-2019-builds.pkr.hcl
      - name: Update Docker
        run: |
          docker push oilrich25/runner-images:windows-2019-builds
